#!/usr/bin/env bash
# Script that creates and deletes file

signal()
{
	echo "I hate the kill command"
	rm -f /var/run/myscript.pid
}

second_signal()
{
	echo "Y U no love me?!"
}

trap signal SIGTERM SIGQUIT
trap second_signal SIGINT

echo $$ >> /var/run/myscript.pid

while true
do :
	echo "To infinity and beyond"
done
