#!/usr/bin/env bash
# a Bash script that displays numbers from 1 to 100 replacing numbers with
#+ fizz, buzz or fizzbuzz where necessary

i=1
while [ $i -le 100 ]
do :
	if [ $((i % 15)) -eq 0 ]
	then
		echo "FizzBuzz"
	elif [ $((i % 5)) -eq 0 ]
	then
		echo "Buzz"
	elif [ $((i % 3)) -eq 0 ]
	then
		echo "Fizz"
	else
		echo "$i"
	fi
	((i++))
done
